# Легенда классов датасета Hessigheim 3D (H3D)
# Источник: Kölle et al. 2021, ISPRS Open Journal of Photogrammetry and Remote Sensing
# https://arxiv.org/abs/2102.05346

classes:
  0: "Низкая растительность"
  1: "Непроницаемая поверхность"
  2: "Транспортное средство"
  3: "Городская мебель"
  4: "Крыша"
  5: "Фасад"
  6: "Кустарник"
  7: "Дерево"
  8: "Грунт/гравий"
  9: "Вертикальная поверхность"
  10: "Дымовая труба"
